[
  {
    "id": "1",
    "icon": "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    "style": "Nike Air Monarch IV",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "200",
    "company": "Nike",
    "color": "white",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "2",
    "icon": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    "style": "Nike Air Vapormax Plus",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "200",
    "company": "Nike",
    "color": "red",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "3",
    "icon": "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    "style": "Nike Waffle One Sneaker",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "200",
    "company": "Nike",
    "color": "green",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "4",
    "icon": "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    "style": "Nike Running Shoe",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "200",
    "company": "Adidas",
    "color": "black",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "5",
    "icon": "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    "style": "Flat Slip On Pumps",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "200",
    "company": "Vans",
    "color": "green",
    "category": "flats",
    "amount":"1"
  },
  {
    "id": "6",
    "icon": "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    "style": "Knit Ballet Flat",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "50",
    "company": "Adidas",
    "color": "black",
    "category": "flats",
    "amount":"1"
  },
  {
    "id": "7",
    "icon": "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    "style": "Loafer Flats",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "50",
    "company": "Vans",
    "color": "white",
    "category": "flats",
    "amount":"1"
  },
  {
    "id": "8",
    "icon": "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    "style": "Nike Zoom Freak",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "200",
    "company": "Nike",
    "color": "green",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "9",
    "icon": "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    "style": "Nike Men's Sneaker",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "200",
    "company": "Adidas",
    "color": "blue",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "10",
    "icon": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    "style": "PUMA BLACK-OCE",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "150",
    "company": "Puma",
    "color": "green",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "11",
    "icon": "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    "style": "Pacer Future Sneaker",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "150",
    "company": "Puma",
    "color": "red",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "12",
    "icon": "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    "style": "Unisex-Adult Super",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "150",
    "company": "Puma",
    "color": "black",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "13",
    "icon": "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    "style": "Roma Basic Sneaker",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "150",
    "company": "Puma",
    "color": "white",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "14",
    "icon": "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    "style": "Pacer Future Doubleknit",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "150",
    "company": "Puma",
    "color": "black",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "15",
    "icon": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    "style": "Fusion Evo Golf Shoe",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "100",
    "company": "Puma",
    "color": "green",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "16",
    "icon": "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    "style": "Rainbow Chex Skate",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "100",
    "company": "Vans",
    "color": "red",
    "category": "flats",
    "amount":"1"
  },
  {
    "id": "17",
    "icon": "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    "style": "Low-Top Trainers",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "100",
    "company": "Vans",
    "color": "white",
    "category": "sandals",
    "amount":"1"
  },
  {
    "id": "18",
    "icon": "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    "style": "Vans Unisex Low-Top",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "100",
    "company": "Vans",
    "color": "blue",
    "category": "sandals",
    "amount":"1"
  },
  {
    "id": "19",
    "icon": "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    "style": "Classic Bandana Sneakers",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "50",
    "company": "Nike",
    "color": "black",
    "category": "sandals",
    "amount":"1"
  },
  {
    "id": "20",
    "icon": "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    "style": "Chunky High Heel",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "50",
    "company": "Vans",
    "color": "black",
    "category": "heels",
    "amount":"1"
  },
  {
    "id": "21",
    "icon": "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    "style": "Slip On Stiletto High Heel",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "100",
    "company": "puma",
    "color": "black",
    "category": "heels",
    "amount":"1"
  },
  {
    "id": "22",
    "icon": "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    "style": "DREAM PAIRS Court Shoes",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "150",
    "company": "Nike",
    "color": "red",
    "category": "heels",
    "amount":"1"
  },
  {
    "id": "23",
    "icon": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    "style": "Nike Air Vapormax Plus",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "200",
    "company": "Nike",
    "color": "red",
    "category": "sneakers",
    "amount":"1"
  },
  {
    "id": "24",
    "icon": "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    "style": "Low Mid Block Heels",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "200",
    "company": "Nike",
    "color": "black",
    "category": "heels",
    "amount":"1"
  },
  {
    "id": "25",
    "icon": "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    "style": "Chunky High Heel",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "50",
    "company": "Adidas",
    "color": "black",
    "category": "heels",
    "amount":"1"
  },
  {
    "id": "26",
    "icon": "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    "style": "Amore Fashion Stilettos",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "150",
    "company": "Adidas",
    "color": "white",
    "category": "heels",
    "amount":"1"
  },
  {
    "id": "27",
    "icon": "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    "style": "Bridal Sandals Glitter",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "50",
    "company": "Adidas",
    "color": "black",
    "category": "heels",
    "amount":"1"
  },
  {
    "id": "28",
    "icon": "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    "style": "Wedding Prom Bridal",
    "reviews": "(123 reviews)",
    "prevPrice": "$140,00",
    "price": "50",
    "company": "Adidas",
    "color": "black",
    "category": "flats",
    "amount":"1"
  }
]